spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school-manegement
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    #initialization-mode: always
  jpa:
    hibernate:
      ddl: create
