spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventrydbs1?createDatabaseIfNotExist=true
    username: root
    password: Virtusa@1234
    driverClassName: com.mysql.cj.jdbc.Driver
    #initialization-mode: always
